### PR TITLE
Release 1.41.1 Added FlashBlade REST 2.11 fix

### PR DESCRIPTION
**Pull request by rlucan-ps**
- Fixes SMB encryption & Deny statements methods of released 1.41 version (FB API 2.11) which did not support newly added attributes.
- Adds SDK examples for the Deny statement.

### CODE REVIEW

**Comment by sdodsley** [comment]
@rlucan-ps is this just fixing the docs or the underlying issue as well? Looks like just the docs

**Comment by rlucan-ps** [comment]
> @rlucan-ps is this just fixing the docs or the underlying issue as well? Looks like just the docs

I've build the package before this commit and double checked the package that it fixes the underlaying issue as well.

**Review by sdodsley — APPROVED** [review]
LGTM

**Review by Gregory-Bessonov — COMMENTED** [review]
LGTM

**Pull request merged**
