### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by lvicainne**
Upgrade the requests package dependance from <=2.25.1 to <=2.28.1

### CODE REVIEW

**Review by sdodsley — COMMENTED** [review]
Unfortunatley, it's not as easy as just changing the upper constraint.
We have to internally test these changes across all 3 platforms that are supported by this package.
I will raise this PR with the internal engineering teams.

**Comment by lvicainne** [comment]
Hello @sdodsley,
Thanks a lot for considering this merge request.
My scripts are using other python packages that requires requests > 2.25.1 (and I get currently a not resolved dependancy)
Kind regards

**Comment by Gregory-Bessonov** [comment]
Hello @lvicainne,
FYI: we are working on dependencies review right now and expect to extend version support for number of the dependencies including requests package. Thus, there is a high chance that desired change will be a part of the next release.
Thank you!

**Comment by lvicainne** [comment]
Thank you @Gregory-Bessonov !
I had to find another solution during these 8 last months for my company business working
Kind regards

**Pull request closed without merging**
